### ISSUE TITLE
Frontend: Add possibility to add a new product

### ISSUE THREAD

**Issue by pr0xity** [pr0xity/Urban-Infusion#36]
Add possibility to add a new product

**Comment by pr0xity** [comment]
Remember to ensure the product have an image before adding, might have placeholder image if none provided.

**Comment by pr0xity** [comment]
Adding new product w/o image is implemented

TODO: images
TODO: stock image is not added
TODO: make overlay disappear when clicking outside it or the x-mark

**Comment by janitaroyseth** [comment]
Adding product with image is implemented.

TODO: stock image is not added
TODO: make overlay disappear when clicking outside it or the x-mark
